on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - run: pip install -r requirements.txt pyinstaller
    - run: pyinstaller -y --distpath dist/linux main_linux.spec
    - uses: actions/upload-artifact@v3
      with:
        name: JellyPlayer_Linux
        path: |
              dist/*
