on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
jobs:
  build:
    runs-on: 'macos-latest'

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - run: pip install -r requirements.txt pyinstaller
    - run: pyinstaller --windowed --name JellyPlayer --icon assets/icon.icns --osx-bundle-identifier "prayag17.jellyplayer.0.1.0" main.py
    - uses: actions/upload-artifact@v3
      with:
        name: JellyPlayer
        path: |
              dist/*
              main.spec
